name: Test Secret

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret presence
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
            echo "MY_SECRET is empty or not set"
          else
            echo "MY_SECRET is set (value will be masked)"
            echo "${{ secrets.DOCKER_HUB_TOKEN }}"
          fi
